name: Deploy Web App to Azure

on:
  push:
    branches: ["*"]
    paths:
      - "src/AlbumViewerAngular/**"
      - ".github/workflows/deploy-web.yml"
  workflow_dispatch:

env:
  WEB_APP_NAME: kiz-albumviewer-web
  API_APP_NAME: kiz-albumviewer-api
  WEB_PROJECT_PATH: src/AlbumViewerAngular

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "src/AlbumViewerAngular/package-lock.json"

      - name: Install dependencies
        run: |
          cd ${{ env.WEB_PROJECT_PATH }}
          npm ci

      - name: Build Angular app
        run: |
          cd ${{ env.WEB_PROJECT_PATH }}
          npm run build -- --configuration=production

          # Generate env.js file with API URL
          API_URL="https://${{ env.API_APP_NAME }}.azurewebsites.net"
          echo "Generating env.js with API_URL: $API_URL"

          # Create env.js file directly in dist folder
          cat > dist/env.js << EOF
          (function(window) {
            window.__env = window.__env || {};
            window.__env.API_URL = '$API_URL';
          })(this);
          EOF

          # Copy other required files
          cp src/web.config dist/

          echo "Build completed. Contents of dist folder:"
          ls -la dist/

      - name: Create deployment package
        run: |
          cd ${{ env.WEB_PROJECT_PATH }}
          # Create a deployment folder with the contents that should go to wwwroot
          mkdir -p deployment
          cp -r dist/* deployment/
          
          echo "Deployment package contents:"
          ls -la deployment/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Angular app to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          package: ${{ env.WEB_PROJECT_PATH }}/deployment

      - name: Verify Web deployment
        run: |
          echo "🎉 Web app deployment completed!"
          echo "📍 Web app deployed to: https://${{ env.WEB_APP_NAME }}.azurewebsites.net"

          # Wait a moment for deployment to complete
          sleep 30

          # Test the web app endpoint
          WEB_URL="https://${{ env.WEB_APP_NAME }}.azurewebsites.net"
          echo "Testing Web app at: $WEB_URL"
          curl -f "$WEB_URL" || echo "Web app verification failed, but deployment completed"
